### ISSUE TITLE
Stream 3 - Questions

### ISSUE THREAD

**Issue by jwagemann** [esowc/challenges_2020#11]
# Propose your own project idea to receive cloud credits from the European Weather Cloud

> Stream 3  - Cloud-based weather and climate innovations

> **IMPORTANT**: this challenge is **ONLY** eligible to apply for cloud credits from European Weather Cloud.

### Goal
Do you have a project idea that makes use of ECMWF or Copernicus open data but you would need cloud processing resources to process the data? This is your chance to get access to cloud credits and gain experience in cloud computing.

### Mentors and eligibility requirements
* **Mentors:**
  * you will get assistance (if needed) on how to use cloud services and we will follow up the progress of your project during the coding period
* **Requirements**
  * Your project has to be related to a weather, climate or atmospheric application

### Who is it for?
* Are you a student with an idea for your final student project that requires cloud computing resources?
* Are you interested in geospatial cloud services, but you never had a chance to work with cloud services?

### What does a good proposal make?
* it is well structured and precise
* the solution proposed is technically feasible within 4 months
* it contains a clear timeline with milestones and deliverables defined

An example structure could be:
1. Brief description of the problem to be solved
2. Proposed solution (including AWS tools, data used and link to [AWS Simply Monthly calculator](https://calculator.s3.amazonaws.com/index.html))
3. Key milestones and deliverables
4. Timeline
5. Plans to share the project outcomes

### Questions
Post here any question related to Stream 3.

**Comment by DebDx** [comment]
The projects have to be an end product or can it be a research based project?

**Comment by milankl** [comment]
@jwagemann as I don't where else to ask: Is it mandatory to present on Sept 18 in person or could this also be done virtually? I'm currently investigating options to shift/postpone a few other projects that I'm involved with around coronavirus-related travel restrictions and it could be that one of these projects will take place in Sept/Oct such that I would be able to work on ESoWC beforehand, but might be unable to attend in Sept in person, although attending in person is a clear preference for me. In my case this wouldn't impact my chance to meet mentors as I'm Oxford-based, but just to check what your policies are.

**Comment by jwagemann** [comment]
Hi @DebDx ,
the projects can be research based as well.

**Comment by jwagemann** [comment]
Hi @milankl ,
there was a change in the date of the final ESoWC day @ECMWF anyway. It will now be the 25 September 2020. Even though we encourage in-person attendance, we understand that the date is not optimal for everyone. We have live-streaming capabilities, thus there will be the option to present the project results from remote.

**Comment by milankl** [comment]
Thanks Julia for the info, Sept 25 sounds good!

**Comment by jwagemann** [comment]
Join us for our LIVE @ecmwf Summer of Weather Code Ask Me Anything session on 1 April 2020 at 2 pm (CET) (tomorrow).

Get infos first hand from the #ESoWC2020 organisers, mentors and former #ESoWC participants.
➡️[Sign up](https://esowc.ecmwf.int/ama)

**Comment by saferplaces** [comment]
This IPR is valid also in Stream3 “Participant grants ECMWF a free, non-exclusive, irrevocable, worldwide, transferable, sub-licensable and perpetual license to use all such intellectual property rights as are necessary for the use of the Deliverables, including for their maintenance, modification, and replacement by or on behalf of ECMWF”

**Comment by saferplaces** [comment]
For Stream3 there is any template for the proposal?

**Comment by jwagemann** [comment]
Hi @saferplaces regarding the IPR related to Stream 3: you raise a valid point here as the projects under Stream 3 will be more of an explorative nature. I'll consolidate with our legal department and will get back to you.

Concerning a template for the proposal: we do not have a template per se, but we will provide some guidelines on what makes a good proposal.

**Comment by saferplaces** [comment]
Thanks a lot!! Yes for Stream 3 I would suggest to leave IPR to the developers if possibile. Thanks

**Comment by jwagemann** [comment]
Hi @saferplaces . Concerning the IPR:
- Art. 5(2) in the [ESoWC Terms and Conditions](https://esowc.ecmwf.int/terms-and-conditions)  states to grant ECMWF a restricted license solely to choose the proposals under Stream 3
- Art. 5(3) only addresses deliverables under Stream 1 and Stream 2.

Hope this helps.

**Comment by jwagemann** [comment]
> For Stream3 there is any template for the proposal?

I added an example how a proposal could be structured.

**Comment by timokelder** [comment]
Hi,
I'm Timo, a PhD student at Loughborough University studying weather and climate extremes. Together with a team at Loughborough, Oxford and ECMWF (and anyone interested), we would like to propose the following [project](https://timokelder.github.io/UNSEEN-open/) but we would welcome some advice/opinions on whether the project fits the scope of esowc. Our project proposes to use seasonal forecasts from ECMWF (SEAS5) to assess the characteristics of past weather extremes. In particular, we would propose to study the likelihood of occurrence of last february's precipitation amount over the UK, that was the highest on record and has caused widespread disruption. The large amount of forecasted february precipitation events within the SEAS5 hindcast can be used to put the observed record into perspective -- a method that has been called the UNprecedented Simulated Extreme ENsemble ([UNSEEN](https://www.nature.com/articles/s41467-017-00275-3)). We would develop an open workflow to apply this idea to SEAS5, that would be easily transferable to other regions and variables of interest, such as hurricanes over America or monsoon precipitation over India, and would be of great interest to data scarce areas by providing a workflow to obtain a large dataset on important climate variables over the past decades.

We believe this workflow would be of interest to ECMWF because it enables an alternative use of the SEAS5 system (applicable to a range of extremes). We are very open to further develop this project together with ECMWF mentors and to discuss the best way to approach the project, also if this project might not be fit for esowc. A starting short description on the project: https://timokelder.github.io/UNSEEN-open/ / https://github.com/timokelder/UNSEEN-open

**Comment by milankl** [comment]
>  Our project proposes to use seasonal forecasts from ECMWF (SEAS5) to assess the characteristics of past weather extremes.

Just out of interest, how realistic is the SEAS5 ensemble spread?

**Comment by milankl** [comment]
@joshdorrington interesting?

**Comment by timokelder** [comment]
> Just out of interest, how realistic is the SEAS5 ensemble spread?

I suppose it really depends on the target variable and region, but evaluation would definitely be a very important part of the workflow!

**Comment by milankl** [comment]
> > Just out of interest, how realistic is the SEAS5 ensemble spread?
> 
> I suppose it really depends on the target variable and region, but evaluation would definitely be a very important part of the workflow!

Well, you mentioned precipitation 🤔

**Comment by timokelder** [comment]
> > > Just out of interest, how realistic is the SEAS5 ensemble spread?
> > 
> > 
> > I suppose it really depends on the target variable and region, but evaluation would definitely be a very important part of the workflow!
> 
> Well, you mentioned precipitation 🤔

For UK winter precipitation extremes we should be alright, since they are driven by large scale weather systems (e.g. Atmospheric rivers) that SEAS5 (36km horizontal resolution) is able to solve

**Comment by jwagemann** [comment]
Only 4 days left to apply to be part of ECMWF Summer of Weather Code 2020. 
Application deadline: **Wednesday, 22 April 2020 at 23:59 (BST)**. 
Submit your proposal [here](https://esowc.commpla.com/form/application-form).
